EasyStocks/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path(
        'robots.txt',
        TemplateView.as_view(
            template_name="robots.txt",
            content_type='text/plain'
        )
    ),
    path(
        'sitemap.xml',
        TemplateView.as_view(
            template_name="sitemap.xml",
            content_type='text/plain')
        ),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('accounts.urls')),
    path('', include('stocks.urls')),
]

stocks/urls.py
from django.urls import path
from .views import ShareListView, ShareDetailView

urlpatterns = [
    path('', ShareListView.as_view(), name='home'),
    path(
        'share/<int:share_id>/delete_article/<int:article_id>/',
        ShareDetailView.delete_article,
        name='delete_article'
    ),
    path('share/<int:pk>/', ShareDetailView.as_view(), name='share_detail'),
]

stocks/models.py
from django.db import models
from django.utils.timezone import now


class MarketDataProvider(models.Model):
    '''
    MarketDataProvider class represents market data source
    '''
    title = models.CharField(max_length=200)
    url = models.CharField(max_length=200)
    folder = models.CharField(max_length=200)

    def __str__(self):
        return self.title


class Share(models.Model):
    '''
    Share class represents share instrument
    '''
    title = models.CharField(max_length=200)
    ticker = models.CharField(max_length=10)
    text = models.TextField()
    countryCode = models.CharField(max_length=3)
    sector = models.CharField(max_length=30)
    dataProvider = models.ForeignKey(
        'MarketDataProvider',
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )
    currency = models.ForeignKey(
        'Currency',
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )
    competitors = models.ManyToManyField('Share')

    def __str__(self):
        return self.title


class ShareDataItem(models.Model):
    '''
    ShareDataItem class represents share statistics
    at specific date
    '''
    share = models.ForeignKey(
        'Share',
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )
    date = models.DateField()
    open_price = models.FloatField()
    high_price = models.FloatField()
    low_price = models.FloatField()
    close_price = models.FloatField()
    volume = models.FloatField()

    def __str__(self):
        return self.share.__str__() + ' ' + str(self.date)


class CurrencyInstrument(models.Model):
    title = models.CharField(max_length=200)
    ticker = models.CharField(max_length=10)
    base_currency = models.CharField(max_length=10)
    instrument_currency = models.CharField(max_length=10)
    text = models.TextField()

    def __str__(self):
        return self.title


class Article(models.Model):
    author = models.CharField(max_length=200, blank=True)
    title = models.TextField(blank=True)
    description = models.TextField(blank=True)
    url = models.URLField(blank=True)
    url_to_image = models.URLField(blank=True)
    content = models.TextField(blank=True)
    publish_dateTime = models.DateTimeField(blank=True)
    share = models.ForeignKey(
        'Share',
        on_delete=models.CASCADE,
        null=True
    )

    def __str__(self):
        return str(self.share) + ' ' + self.title

    @staticmethod
    def are_valid_arguments(article_dict):
        if not article_dict['author']:
            return False
        if not article_dict['title']:
            return False
        if not article_dict['description']:
            return False
        if not article_dict['url']:
            return False
        if not article_dict['urlToImage']:
            return False
        if not article_dict['content']:
            return False
        return True

    @staticmethod
    def get_source_name(article_dict):
        source = article_dict['source']
        return source['name']


class Dividend(models.Model):
    amount = models.FloatField()
    date = models.DateField(default=now)
    share = models.ForeignKey(
        'Share',
        on_delete=models.CASCADE,
        null=True
    )
    currency = models.ForeignKey(
        'Currency',
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )

    def __str__(self):
        return self.share.__str__()


class Product(models.Model):
    name = models.CharField(max_length=200, blank=True)
    revenue = models.IntegerField()
    date = models.DateField(default=now)
    share = models.ForeignKey(
        'Share',
        on_delete=models.CASCADE,
        null=True
    )

    def __str__(self):
        return self.name


class Indicators(models.Model):
    revenue = models.IntegerField()
    earnings = models.IntegerField()
    date = models.DateField(default=now)
    share = models.ForeignKey(
        'Share',
        on_delete=models.CASCADE,
        null=True
    )

    def __str__(self):
        return self.share.__str__() + ' (' + str(self.date) + ')'


class Customer(models.Model):
    location = models.CharField(max_length=200, blank=True)
    percentage = models.IntegerField()
    date = models.DateField(default=now)
    share = models.ForeignKey(
        'Share',
        on_delete=models.CASCADE,
        null=True
    )

    def __str__(self):
        return self.share.__str__() + ' ' + self.location


class Currency(models.Model):
    name = models.CharField(max_length=200, blank=True)
    symbol = models.CharField(max_length=10, blank=True)

    def __str__(self):
        return self.name

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>EasyStocks</title>
  <meta name="description" content="The project for market trends visualization">
  <meta name="author" content="ivan">
  <!-- Favicons -->
  <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">
  <!-- Bootstrap -->
  <link rel="stylesheet" type="text/css"  href="{% static 'css/bootstrap.css' %}">
  <!-- Stylesheet -->
  <link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/owl.carousel.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/owl.theme.default.min.css' %}">
  <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,500,600,700" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Oswald" rel="stylesheet">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.bundle.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  <script src="{% static 'js/owl.carousel.min.js' %}"></script>
  <script src="{% static 'js/custom.js' %}"></script>
</head>
{% block content %}
{% endblock content %}
</html>

templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>EasyStocks</title>
  <meta name="description" content="Сервис для начинающих инвесторов">
  <meta name="author" content="Ivan Abramov">
  <!-- Favicons -->
  <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">
  <!-- Bootstrap -->
  <link rel="stylesheet" type="text/css"  href="{% static 'css/bootstrap.css' %}">
  <!-- Stylesheet -->
  <link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/owl.carousel.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/owl.theme.default.min.css' %}">
  <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,500,600,700" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Oswald" rel="stylesheet">
  <!-- Yandex.Metrika counter -->
  <meta name="yandex-verification" content="4b8c05dffb8c79db" />
  <script type="text/javascript" >
    (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
    m[i].l=1*new Date();k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
    (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

    ym(53274031, "init", {
        clickmap:true,
        trackLinks:true,
        accurateTrackBounce:true
    });
  </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.bundle.js"></script>
  <noscript><div><img src="https://mc.yandex.ru/watch/53274031" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
  <!-- /Yandex.Metrika counter -->
  <!-- Google -->
  <meta name="google-site-verification" content="-ppnG-4W_XI-BeCO8A3X1h0gHNriVbMAb2YTDsOhfHY" />
  <!-- /Google-->
</head>
<body>
  <!-- Navigation -->
  <nav id="navigation" class="navbar navbar-inverse navbar-static-top">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#home-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="home-collapse">
        <ul class="nav navbar-nav navbar-left">
          <a class="navbar-brand" href="{% url 'home' %}">EasyStocks</a>
        </ul>
        {% if not user.is_authenticated %}
        <ul class="nav navbar-nav navbar-right">
          <li>
            <a href="{% url 'login' %}">Войти</a>
          </li>
          <li>
            <a href="{% url 'signup' %}">Регистрация</a>
          </li>
        </ul>
        {% else %}
        <ul class="nav navbar-nav navbar-right">
          <li>
            <a href="{% url 'personal' user.pk %}">Личный кабинет</a>
          </li>
          <li>
            <a href="{% url 'logout' %}">Выйти</a>
          </li>
        </ul>
        {% endif %}
      </div>
    </div>
  </nav>
  <!-- Header -->
  <header id="header">
    <div class="intro">
      <div class="overlay">
        <div class="container">
          <div class="row">
            <div class="col-xs-12">
              <div class="intro-text">
                <h1>EasyStocks</h1>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>
  <!-- About -->
  <div id="about">
    <div class="container-fluid">
      <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-6">
          <div class="about-text">
            <h3 class="text-center">Сервис для инвесторов</h3>
            <p class="text-center">Поможем сформировать инвестиционный портфель <br> Напомним про важные события на фондовом и валютном рынке </p>
          </div>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-6">
          <div class="about-text">
            <h3 class="text-center">Статистика</h3>
            {% block statistics %}
              <p class="text-center">
                Количество акций: {{ share_list|length }} <br> 
                Количество валютных пар: {{ currency_list|length }} <br>
                Количество новостей: {{ news_list|length }}
              </p>
            {% endblock statistics %}
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Stocks -->
  <div id="stocks" class="text-center">
    <div class="container">
      <div class="section-title">
        <h2>Акции 🇺🇸</h2>
      </div>
      <div class="container">
        {% block content %}
          <div class="row">
            <div id="tech-usa-stock-carousel" class="owl-carousel owl-theme">
              {% for share in tech_usa %}
                <a href="{% url 'share_detail' share.pk %}">
                  <div class="chart">
                    <h3 class="text-center">{{ share.title }}</h3>
                    <img src="{% get_static_prefix %}img/stocks/{{ share.ticker }}.png" class="img-responsive" alt="">
                  </div>
                </a>
              {% endfor %}
            </div>
            <div class="row">
              <div id="non-tech-usa-stock-carousel" class="owl-carousel owl-theme">
                {% for share in non_tech_usa %}
                  <a href="{% url 'share_detail' share.pk %}">
                    <div class="chart">
                      <h3 class="text-center">{{ share.title }}</h3>
                      <img src="{% get_static_prefix %}img/stocks/{{ share.ticker }}.png" class="img-responsive" alt="">
                    </div>
                  </a>
                {% endfor %}
              </div>
            </div>
          </div>
        {% endblock content %}
    </div>
  </div>
  <!-- Stocks Russia -->
  <div id="stocks" class="text-center">
    <div class="container">
      <div class="section-title">
        <h2>Акции 🇷🇺</h2>
      </div>
      <div class="container">
        {% block content_rus %}
          <div clas="row">
            <div id="non-materials-rus-stock-carousel" class="owl-carousel owl-theme">
              {% for share in non_materials_rus %}
                <a href="{% url 'share_detail' share.pk %}">
                  <div class="chart">
                    <h3 class="text-center">{{ share.title }}</h3>
                    <img src="{% get_static_prefix %}img/stocks/{{ share.ticker }}.png" class="img-responsive" alt="">
                  </div>
                </a>
              {% endfor %}
            </div>
          </div>
          <div class="row">
            <div id="materials-rus-stock-carousel" class="owl-carousel owl-theme">
              {% for share in materials_rus %}
                <a href="{% url 'share_detail' share.pk %}">
                  <div class="chart">
                    <h3 class="text-center">{{ share.title }}</h3>
                    <img src="{% get_static_prefix %}img/stocks/{{ share.ticker }}.png" class="img-responsive" alt="">
                  </div>
                </a>
              {% endfor %}
            </div>
          </div>
        {% endblock content_rus %}
    </div>
  </div>
  <div id="dividends" class="text-center">
    <div class="container">
      <div class="section-title">
        <h2>Дивиденды</h2>
      </div>
      <div class="row">
        <div id="div-carousel" class="owl-carousel owl-theme">
        {% for dividend in dividends %}
          <div class="item">
            <h3 class="text-center">{{ dividend.share }}</h3>
            <h4>{{ dividend.amount }} {{ dividend.currency.symbol|safe }}</h4>
            <h5>{{ dividend.date }}</h5>
          </div>
        {% endfor %}
        </div>
      </div>
    </div>
  </div>
  <!-- FX -->
  <div id="fx" class="text-center">
    <div class="container">
      <div class="section-title">
        <h2>FX</h2>
      </div>
      <div class="row">
        <div id="currency-carousel" class="owl-carousel owl-theme">
        {% for fx_item in currency_list %}
          <div class="item">
            <h3 class="text-center">{{ fx_item.title }}</h3>
            <img src="{% get_static_prefix %}img/currency/{{ fx_item.ticker }}.png" class="img-responsive" alt="">
          </div>
        {% endfor %}
        </div>
      </div>
    </div>
  </div>
  <!-- Overall -->
  <div id="overall" class="text-center">
    <div class="container">
      <div class="section-title">
        <h2>Итоги</h2>
      </div>
      <div class="row">
        <div id="pie-results-carousel" class="owl-carousel owl-theme">
          <div>
            {% block trends_chart_usa %}
              <canvas id="doughnut-chart-usa"></canvas>
              <script>
                var data = {
                    datasets: [{
                        data: {{ share_usa_trends }},
                        backgroundColor: [
                          "#32CD32",
                          "#FF4500",
                        ],
                    }],
                    labels: [
                        'Рост',
                        'Падение'
                    ]
                };
                var options = {
                  responsive: true,
                  legend: {
                    position: 'top',
                  },
                  title: {
                    display: true,
                    text: 'Итоги недели акций 🇺🇸',
                  },
                  animation: {
                    animateScale: true,
                    animateRotate: true
                  }
                }
                var myDoughnutChart = new Chart(document.getElementById("doughnut-chart-usa"), {
                    type: 'doughnut',
                    data: data,
                    options: options
                });
              </script>
            {% endblock trends_chart_usa %}
          </div>
          <div>
            {% block trends_chart_rus %}
              <canvas id="doughnut-chart-rus"></canvas>
              <script>
                var data = {
                    datasets: [{
                        data: {{ share_rus_trends }},
                        backgroundColor: [
                          "#32CD32",
                          "#FF4500",
                        ],
                    }],
                    labels: [
                        'Рост',
                        'Падение'
                    ]
                };
                var options = {
                  responsive: true,
                  legend: {
                    position: 'top',
                  },
                  title: {
                    display: true,
                    text: 'Итоги недели акций 🇷🇺',
                  },
                  animation: {
                    animateScale: true,
                    animateRotate: true
                  }
                }
                var myDoughnutChart = new Chart(document.getElementById("doughnut-chart-rus"), {
                    type: 'doughnut',
                    data: data,
                    options: options
                });
              </script>
            {% endblock trends_chart_rus %}
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Footer -->
  <div id="footer">
    <div class="container text-center">
      <div class="col-xs-12">
        <p>&copy; 2020 EasyStocks (<a href="https://github.com/airvan21">airvan21</a>)</p>
      </div>
    </div>
  </div>
</body>
<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/custom.js' %}"></script>
</html>

templates/personal.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<body>
  <nav id="navigation" class="navbar navbar-inverse navbar-static-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#share_detail-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div class="collapse navbar-collapse" id="share_detail-collapse">
        <ul class="nav navbar-nav navbar-left">
          <a class="navbar-brand" href="{% url 'home' %}">EasyStocks</a>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li>
            <a href="{% url 'logout' %}">Выйти</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="text-center" id="personal-sections">
    <div class="container">
      <h2>Личный кабинет</h2>
      <div class="row center">
        <div class="box">
          <div class="card col-xs-12 col-sm-6 col-md-4">
            <div class="imgBx">
              <img src="{% static 'img/portfolio-small.jpg' %}" class="img-responsive">
            </div>
            <div class="details">
              <h2>Портфель</h2>
            </div>
          </div>
          <div class="card col-xs-12 col-sm-6 col-md-4">
            <div class="imgBx">
              <img src="{% static 'img/trade-small.jpg' %}" class="img-responsive">
            </div>
            <div class="details">
              <h2>Сделки</h2>
            </div>
          </div>
          <div class="card col-xs-12 col-sm-6 col-md-4">
            <div class="imgBx">
              <img src="{% static 'img/dividends.jpeg' %}" class="img-responsive">
            </div>
            <div class="details">
              <h2>Дивиденды</h2>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="text-center" id="personal-portfolio">
    <div class="container">
      <table class="table">
        <thead>
          <tr>
            <th scope="col">Тикер</th>
            <th scope="col">Название</th>
            <th scope="col">Страна</th>
            <th scope="col">Сектор</th>
          </tr>
        </thead>
        <tbody>
          {% block personal_deals %}
            {% for share in portfolio_shares %}
              <tr>
                <td>{{ share.ticker }}</td>
                <td>{{ share.title }}</td>
                <td>{{ share.countryCode }}</td>
                <td>{{ share.sector }}</td>
              </tr>
            {% endfor %}
          {% endblock personal_deals %}
        </tbody>
      </table>
    </div>
  </div>
</body>
{% endblock content %}

templates/signup.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<body>
  <nav id="navigation" class="navbar navbar-inverse navbar-static-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#share_detail-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div class="collapse navbar-collapse" id="share_detail-collapse">
        <ul class="nav navbar-nav navbar-left">
          <a class="navbar-brand" href="{% url 'home' %}">EasyStocks</a>
        </ul>
      </div>
    </div>
  </nav>
  <div class="text-center">
    <div class="container-fluid">
      <h2>Регистрация</h2>
      <form method="post" id="signup-form">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-success ml-2" type="submit">Регистрация</button>
      </form>
    </div>
  </div>
<body>
{% endblock content %}